package com.kstech.zoomlion.model.db.greendao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import com.kstech.zoomlion.model.db.CheckItemData;

import com.kstech.zoomlion.model.db.AuthorizeRecord;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "AUTHORIZE_RECORD".
*/
public class AuthorizeRecordDao extends AbstractDao<AuthorizeRecord, Long> {

    public static final String TABLENAME = "AUTHORIZE_RECORD";

    /**
     * Properties of entity AuthorizeRecord.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property AuthorizedId = new Property(0, Long.class, "authorizedId", true, "_id");
        public final static Property ItemId = new Property(1, Long.class, "itemId", false, "ITEM_ID");
        public final static Property CheckerId = new Property(2, Long.class, "checkerId", false, "CHECKER_ID");
        public final static Property AuthorizerName = new Property(3, String.class, "authorizerName", false, "AUTHORIZER_NAME");
        public final static Property AuthorizerId = new Property(4, Long.class, "authorizerId", false, "AUTHORIZER_ID");
        public final static Property AuthorizeTime = new Property(5, java.util.Date.class, "authorizeTime", false, "AUTHORIZE_TIME");
        public final static Property AuthorizeDesc = new Property(6, String.class, "authorizeDesc", false, "AUTHORIZE_DESC");
    }

    private DaoSession daoSession;

    private Query<AuthorizeRecord> checkItemData_AuthorizeRecordsQuery;

    public AuthorizeRecordDao(DaoConfig config) {
        super(config);
    }
    
    public AuthorizeRecordDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"AUTHORIZE_RECORD\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: authorizedId
                "\"ITEM_ID\" INTEGER," + // 1: itemId
                "\"CHECKER_ID\" INTEGER," + // 2: checkerId
                "\"AUTHORIZER_NAME\" TEXT," + // 3: authorizerName
                "\"AUTHORIZER_ID\" INTEGER," + // 4: authorizerId
                "\"AUTHORIZE_TIME\" INTEGER UNIQUE ," + // 5: authorizeTime
                "\"AUTHORIZE_DESC\" TEXT);"); // 6: authorizeDesc
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"AUTHORIZE_RECORD\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, AuthorizeRecord entity) {
        stmt.clearBindings();
 
        Long authorizedId = entity.getAuthorizedId();
        if (authorizedId != null) {
            stmt.bindLong(1, authorizedId);
        }
 
        Long itemId = entity.getItemId();
        if (itemId != null) {
            stmt.bindLong(2, itemId);
        }
 
        Long checkerId = entity.getCheckerId();
        if (checkerId != null) {
            stmt.bindLong(3, checkerId);
        }
 
        String authorizerName = entity.getAuthorizerName();
        if (authorizerName != null) {
            stmt.bindString(4, authorizerName);
        }
 
        Long authorizerId = entity.getAuthorizerId();
        if (authorizerId != null) {
            stmt.bindLong(5, authorizerId);
        }
 
        java.util.Date authorizeTime = entity.getAuthorizeTime();
        if (authorizeTime != null) {
            stmt.bindLong(6, authorizeTime.getTime());
        }
 
        String authorizeDesc = entity.getAuthorizeDesc();
        if (authorizeDesc != null) {
            stmt.bindString(7, authorizeDesc);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, AuthorizeRecord entity) {
        stmt.clearBindings();
 
        Long authorizedId = entity.getAuthorizedId();
        if (authorizedId != null) {
            stmt.bindLong(1, authorizedId);
        }
 
        Long itemId = entity.getItemId();
        if (itemId != null) {
            stmt.bindLong(2, itemId);
        }
 
        Long checkerId = entity.getCheckerId();
        if (checkerId != null) {
            stmt.bindLong(3, checkerId);
        }
 
        String authorizerName = entity.getAuthorizerName();
        if (authorizerName != null) {
            stmt.bindString(4, authorizerName);
        }
 
        Long authorizerId = entity.getAuthorizerId();
        if (authorizerId != null) {
            stmt.bindLong(5, authorizerId);
        }
 
        java.util.Date authorizeTime = entity.getAuthorizeTime();
        if (authorizeTime != null) {
            stmt.bindLong(6, authorizeTime.getTime());
        }
 
        String authorizeDesc = entity.getAuthorizeDesc();
        if (authorizeDesc != null) {
            stmt.bindString(7, authorizeDesc);
        }
    }

    @Override
    protected final void attachEntity(AuthorizeRecord entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public AuthorizeRecord readEntity(Cursor cursor, int offset) {
        AuthorizeRecord entity = new AuthorizeRecord( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // authorizedId
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // itemId
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // checkerId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // authorizerName
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4), // authorizerId
            cursor.isNull(offset + 5) ? null : new java.util.Date(cursor.getLong(offset + 5)), // authorizeTime
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6) // authorizeDesc
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, AuthorizeRecord entity, int offset) {
        entity.setAuthorizedId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setItemId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setCheckerId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setAuthorizerName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setAuthorizerId(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
        entity.setAuthorizeTime(cursor.isNull(offset + 5) ? null : new java.util.Date(cursor.getLong(offset + 5)));
        entity.setAuthorizeDesc(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(AuthorizeRecord entity, long rowId) {
        entity.setAuthorizedId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(AuthorizeRecord entity) {
        if(entity != null) {
            return entity.getAuthorizedId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(AuthorizeRecord entity) {
        return entity.getAuthorizedId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "authorizeRecords" to-many relationship of CheckItemData. */
    public List<AuthorizeRecord> _queryCheckItemData_AuthorizeRecords(Long itemId) {
        synchronized (this) {
            if (checkItemData_AuthorizeRecordsQuery == null) {
                QueryBuilder<AuthorizeRecord> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.ItemId.eq(null));
                checkItemData_AuthorizeRecordsQuery = queryBuilder.build();
            }
        }
        Query<AuthorizeRecord> query = checkItemData_AuthorizeRecordsQuery.forCurrentThread();
        query.setParameter(0, itemId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getCheckItemDataDao().getAllColumns());
            builder.append(" FROM AUTHORIZE_RECORD T");
            builder.append(" LEFT JOIN CHECK_ITEM_DATA T0 ON T.\"ITEM_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected AuthorizeRecord loadCurrentDeep(Cursor cursor, boolean lock) {
        AuthorizeRecord entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        CheckItemData checkItemData = loadCurrentOther(daoSession.getCheckItemDataDao(), cursor, offset);
        entity.setCheckItemData(checkItemData);

        return entity;    
    }

    public AuthorizeRecord loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<AuthorizeRecord> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<AuthorizeRecord> list = new ArrayList<AuthorizeRecord>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<AuthorizeRecord> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<AuthorizeRecord> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
