package com.kstech.zoomlion.model.db.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.kstech.zoomlion.model.db.MsgSetDB;
import com.kstech.zoomlion.model.db.AuthorizeRecord;
import com.kstech.zoomlion.model.db.CheckChartData;
import com.kstech.zoomlion.model.db.CheckImageData;
import com.kstech.zoomlion.model.db.CheckItemData;
import com.kstech.zoomlion.model.db.CheckItemDetailData;
import com.kstech.zoomlion.model.db.CheckRecord;

import com.kstech.zoomlion.model.db.greendao.MsgSetDBDao;
import com.kstech.zoomlion.model.db.greendao.AuthorizeRecordDao;
import com.kstech.zoomlion.model.db.greendao.CheckChartDataDao;
import com.kstech.zoomlion.model.db.greendao.CheckImageDataDao;
import com.kstech.zoomlion.model.db.greendao.CheckItemDataDao;
import com.kstech.zoomlion.model.db.greendao.CheckItemDetailDataDao;
import com.kstech.zoomlion.model.db.greendao.CheckRecordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig msgSetDBDaoConfig;
    private final DaoConfig authorizeRecordDaoConfig;
    private final DaoConfig checkChartDataDaoConfig;
    private final DaoConfig checkImageDataDaoConfig;
    private final DaoConfig checkItemDataDaoConfig;
    private final DaoConfig checkItemDetailDataDaoConfig;
    private final DaoConfig checkRecordDaoConfig;

    private final MsgSetDBDao msgSetDBDao;
    private final AuthorizeRecordDao authorizeRecordDao;
    private final CheckChartDataDao checkChartDataDao;
    private final CheckImageDataDao checkImageDataDao;
    private final CheckItemDataDao checkItemDataDao;
    private final CheckItemDetailDataDao checkItemDetailDataDao;
    private final CheckRecordDao checkRecordDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        msgSetDBDaoConfig = daoConfigMap.get(MsgSetDBDao.class).clone();
        msgSetDBDaoConfig.initIdentityScope(type);

        authorizeRecordDaoConfig = daoConfigMap.get(AuthorizeRecordDao.class).clone();
        authorizeRecordDaoConfig.initIdentityScope(type);

        checkChartDataDaoConfig = daoConfigMap.get(CheckChartDataDao.class).clone();
        checkChartDataDaoConfig.initIdentityScope(type);

        checkImageDataDaoConfig = daoConfigMap.get(CheckImageDataDao.class).clone();
        checkImageDataDaoConfig.initIdentityScope(type);

        checkItemDataDaoConfig = daoConfigMap.get(CheckItemDataDao.class).clone();
        checkItemDataDaoConfig.initIdentityScope(type);

        checkItemDetailDataDaoConfig = daoConfigMap.get(CheckItemDetailDataDao.class).clone();
        checkItemDetailDataDaoConfig.initIdentityScope(type);

        checkRecordDaoConfig = daoConfigMap.get(CheckRecordDao.class).clone();
        checkRecordDaoConfig.initIdentityScope(type);

        msgSetDBDao = new MsgSetDBDao(msgSetDBDaoConfig, this);
        authorizeRecordDao = new AuthorizeRecordDao(authorizeRecordDaoConfig, this);
        checkChartDataDao = new CheckChartDataDao(checkChartDataDaoConfig, this);
        checkImageDataDao = new CheckImageDataDao(checkImageDataDaoConfig, this);
        checkItemDataDao = new CheckItemDataDao(checkItemDataDaoConfig, this);
        checkItemDetailDataDao = new CheckItemDetailDataDao(checkItemDetailDataDaoConfig, this);
        checkRecordDao = new CheckRecordDao(checkRecordDaoConfig, this);

        registerDao(MsgSetDB.class, msgSetDBDao);
        registerDao(AuthorizeRecord.class, authorizeRecordDao);
        registerDao(CheckChartData.class, checkChartDataDao);
        registerDao(CheckImageData.class, checkImageDataDao);
        registerDao(CheckItemData.class, checkItemDataDao);
        registerDao(CheckItemDetailData.class, checkItemDetailDataDao);
        registerDao(CheckRecord.class, checkRecordDao);
    }
    
    public void clear() {
        msgSetDBDaoConfig.clearIdentityScope();
        authorizeRecordDaoConfig.clearIdentityScope();
        checkChartDataDaoConfig.clearIdentityScope();
        checkImageDataDaoConfig.clearIdentityScope();
        checkItemDataDaoConfig.clearIdentityScope();
        checkItemDetailDataDaoConfig.clearIdentityScope();
        checkRecordDaoConfig.clearIdentityScope();
    }

    public MsgSetDBDao getMsgSetDBDao() {
        return msgSetDBDao;
    }

    public AuthorizeRecordDao getAuthorizeRecordDao() {
        return authorizeRecordDao;
    }

    public CheckChartDataDao getCheckChartDataDao() {
        return checkChartDataDao;
    }

    public CheckImageDataDao getCheckImageDataDao() {
        return checkImageDataDao;
    }

    public CheckItemDataDao getCheckItemDataDao() {
        return checkItemDataDao;
    }

    public CheckItemDetailDataDao getCheckItemDetailDataDao() {
        return checkItemDetailDataDao;
    }

    public CheckRecordDao getCheckRecordDao() {
        return checkRecordDao;
    }

}
