package com.kstech.zoomlion.model.db.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.kstech.zoomlion.model.db.MsgSetDB;

import com.kstech.zoomlion.model.db.greendao.MsgSetDBDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig msgSetDBDaoConfig;

    private final MsgSetDBDao msgSetDBDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        msgSetDBDaoConfig = daoConfigMap.get(MsgSetDBDao.class).clone();
        msgSetDBDaoConfig.initIdentityScope(type);

        msgSetDBDao = new MsgSetDBDao(msgSetDBDaoConfig, this);

        registerDao(MsgSetDB.class, msgSetDBDao);
    }
    
    public void clear() {
        msgSetDBDaoConfig.clearIdentityScope();
    }

    public MsgSetDBDao getMsgSetDBDao() {
        return msgSetDBDao;
    }

}
